export const FETCH_TICKET_BY_ID_START = 'FETCH_TICKET_BY_ID_START'
export const FETCH_TICKET_BY_ID_SUCCESS = 'FETCH_TICKET_BY_ID_SUCCESS'
export const FETCH_TICKET_BY_ID_FAILURE = 'FETCH_TICKET_BY_ID_FAILURE'
